-- MySQL Script generated by MySQL Workbench
-- Sat Oct  2 16:11:22 2021
-- Model: New Model    Version: 1.0


-- -----------------------------------------------------
-- Table `movies`
-- -----------------------------------------------------
CREATE TABLE movies
(
  id INT,
  title VARCHAR(45),
  year INT NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table `directors`
-- -----------------------------------------------------
CREATE TABLE directors
(
  id INT NOT NULL,
  Fname VARCHAR(45) NOT NULL,
  Lname VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table actors
-- -----------------------------------------------------
CREATE TABLE actors
(
  id INT NOT NULL,
  Fname VARCHAR(45) NOT NULL,
  Lname VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table writers
-- -----------------------------------------------------
CREATE TABLE writers 
(
  id INT NOT NULL,
  Fname VARCHAR(45) NOT NULL,
  Lname VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table genres
-- -----------------------------------------------------
CREATE TABLE genres
(
  id INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
);


-- -----------------------------------------------------
-- Table rating
-- -----------------------------------------------------
CREATE TABLE rating
(
  votes INT NOT NULL,
  numb_stars INT NOT NULL,
  movies_id INT NOT NULL,
  PRIMARY KEY (movies_id)
);



-- -----------------------------------------------------
-- Table movies_directors
-- -----------------------------------------------------
CREATE TABLE movies_directors 
(
  movies_id INT NOT NULL,
  directors_id INT NOT NULL,
  PRIMARY KEY (movies_id, directors_id),
    -- FOREIGN KEY (movies_id)
    -- FOREIGN KEY (directors_id)
);


-- -----------------------------------------------------
-- Table movies_actors
-- -----------------------------------------------------
CREATE TABLE movies_actors
(
  movies_id INT NOT NULL,
  actors_id INT NOT NULL,
  PRIMARY KEY (movies_id, actors_id),
    -- FOREIGN KEY (movies_id)
    -- FOREIGN KEY (actors_id)
);


-- -----------------------------------------------------
-- Table movies_writers
-- -----------------------------------------------------
CREATE TABLE movies_writers
(
  movies_id INT NOT NULL,
  writers_id INT NOT NULL,
  PRIMARY KEY (movies_id, writers_id),
--     FOREIGN KEY (movies_id)
--     FOREIGN KEY (writers_id)
);


-- -----------------------------------------------------
-- Table movies_genres
-- -----------------------------------------------------
CREATE TABLE movies_has_genres 
(
  movies_id INT NOT NULL,
  genres_id INT NOT NULL,
  PRIMARY KEY (movies_id, genres_id),
    -- FOREIGN KEY (movies_id)
    -- FOREIGN KEY (genres_id)
);